package zipFile.model;

import java.io.Serializable;
import java.sql.Timestamp;

public class UserDetail implements Serializable {
    private Long userId;//Random AutoGenerated
    private String firstName;
    private String lastName;
    private String emailId;
    private String groupName;// [Admin,User]
    private String groupId;// [1,0]
    private Timestamp insertedTimestamp;
    private String insertedBy;
    private Timestamp updatedTimestamp;
    private String updatedBy;
    private String userKey;//

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public Timestamp getInsertedTimestamp() {
        return insertedTimestamp;
    }

    public void setInsertedTimestamp(Timestamp insertedTimestamp) {
        this.insertedTimestamp = insertedTimestamp;
    }

    public String getInsertedBy() {
        return insertedBy;
    }

    public void setInsertedBy(String insertedBy) {
        this.insertedBy = insertedBy;
    }

    public Timestamp getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    public void setUpdatedTimestamp(Timestamp updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public String getUserKey() {
        return userKey;
    }

    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    public String[] getUserRoles() {
        return null;
    }
}
